### ISSUE TITLE
InAppBillingImplementation+InAppBillingServiceConnection.OnServiceConnected (Android.Content.ComponentName name, Android.OS.IBinder service)

### ISSUE THREAD

**Issue by muri61** [jamesmontemagno/InAppBillingPlugin#109] opened 2018-01-23 08:19 UTC
## Bug Information

Version Number of Plugin: 1.2.4
Device Tested On:
Simulator Tested On:
Version of VS: 15.4.1
Version of Xamarin: 4.7.10.22
Versions of other things you are using:

### Steps to reproduce the Behavior
Unknown exactly, I just got a crash report with the stack trace: 
https://gist.github.com/muri61/72c5e134054f693557e9bee7c06eb296

### Expected Behavior
Not crashing

### Actual Behavior
Almost 20 percent of my users are receiving this error.

I've read the InAppBillingPlugin and CurrentActivityPlugin documentations. I also checked the issue in the link https://github.com/jamesmontemagno/InAppBillingPlugin/issues/71. But nothing helped me. Am I missing something. Any help would be appreciated

**Comment by jamesmontemagno** [comment] 2018-01-25 21:33
Duplicate of #75

**Closed by jamesmontemagno** 2018-01-25 21:33 UTC
