### ISSUE TITLE
cannot connect to itunes store 

### ISSUE THREAD

**Issue by waheedkhan-debug** [jamesmontemagno/InAppBillingPlugin#243] opened 2019-09-12 07:55 UTC
Hi Thanks in advance i have facing a problem in my xamarin forms ios. Problem is that when i want to purchase product it thrown an exception that cannot to connect to itune store my same code in working fine on xamarin forms android.My code for restore purchases is working fine.

The screen shot of my problem is here https://i.stack.imgur.com/50iTB.png

**Comment by jamesmontemagno** [comment] 2019-10-07 04:37
It looks like you are running this on a simulator. See my testing guide: https://jamesmontemagno.github.io/InAppBillingPlugin/TestingAndTroubleshooting.html

**Comment by waheedkhan-debug** [comment] 2019-10-07 05:52
Thanks sir for replying , sir i m not testing it on simulator i test it on real device but its not working.It throw an exception,which i mention above in question.

**Comment by slav4ik51493** [comment] 2019-10-10 02:00
I too have this problem on real device.
![image](https://user-images.githubusercontent.com/15287355/66533241-66fe0780-eb3c-11e9-9586-9b59342285ee.png)

**Comment by slav4ik51493** [comment] 2019-10-10 02:13
Additional info: 
I logout from all accounts (real and test) from itunes store and start app. After call on purchase I got dialog for completing Apple ID and Password.
After completing Apple Id and Password, clicked on "Buy" button and got error which I send in previous comment.

**Comment by excellapay** [comment] 2019-11-24 20:08
I have tried the same steps.  I seem to have the same issue. I am definitely communicating with iTunes and get the Subscription product back with a price, but the purchase or verify that it has been purchased is failing.

**Comment by ivanicin** [comment] 2019-12-09 23:14
To share my experience - according to analytics this happens FREQUENTLY, but not to all users.

Not sure if it is the plugin or end user problem. If you search for that problem it is obvious that it happens to a lot of people unrelated to Xamarin.

I guess that it would be worthwhile if you can confirm that you are using the regular App Store account and that you can otherwise make purchases in other apps without the problem.

**Comment by matheuscschenfeld** [comment] 2020-05-04 02:59
Same issue here

**Comment by matheuscschenfeld** [comment] 2020-05-06 01:01
Does anybody solved this issue?

**Comment by excellapay** [comment] 2020-05-06 01:52
Here is what i found.  When it is local or even Test Flight, it does not act right. We release to Production and it worked fine.

**Comment by phyrrus9** [comment] 2020-05-21 19:05
Does anybody have an update on this?

**Comment by blackadder1000** [comment] 2020-06-01 22:29
Having the same issue, anyone have a solution?

**Comment by phyrrus9** [comment] 2020-06-01 22:31
@blackadder1000 my issue was related to the sku of the in app purchase itself. it seems that it must be prefixed by the sku of your app. I also had issues that were resolved by ensuring the contracts were all signed.

**Comment by Meekohi** [comment] 2020-07-29 16:29
Anyone have more info or work-arounds?

**Comment by excellapay** [comment] 2020-07-29 16:36
Sounds bad.  Deploy with TestFlight to your phone and it will likely work.  We have never been able to sandbox or test in beta well. We did all of our final testing with TestFlight and ended up doing real subscptions.  I have it deployed and it works well.

**Comment by Meekohi** [comment] 2020-07-29 21:39
We are having this issue while on real devices with Testflight (production build, but not released yet)

**Comment by phyrrus9** [comment] 2020-07-29 21:43
@Meekohi what worked for me was
1. ensure all contracts were signed
2. make sure that all of your projects have the dependency
3. ensure it is being initialized
4. make your IAP name correctly. For Apple, this must start with your app ID. If your app is com.sample.something and you want to name your IAP com.sample.purchase, it will not work. You need to name it com.sample.something.purchase

With these 4 things, I was able to test, and live purchases also work.

Also keep in mind that for testing, you MUST use a sandbox account, on a blank device (not a simulator).

**Comment by Meekohi** [comment] 2020-07-29 21:48
Sound you say more what you mean by the "sandbox account" and "blank" device requirements? In this case we're trying to debug a specific user who can reproduce this problem, but obviously it's their personal account that we invited to TestFlight.

**Comment by phyrrus9** [comment] 2020-07-29 22:02
> Cound you say more what you mean by the "sandbox account" and "blank" device requirements?

@Meekohi yes. If you log into iTunes Connect, go to "Users and Access" and there will be a tab for sandbox testers. You will need to create one of them, and then log into it on the web portal before using it to finish setup.

As for a blank device, this means a real hardware device that is NOT logged into any account.

When you test your IAP, you will be prompted to log in at that point. It is then that you will use your sandbox credentials to test this. It will not work in TestFlight or Release builds, ONLY debug builds. You can simulate failure or success without generating live charges.

**Comment by Lelelo1** [comment] 2020-11-02 18:19
@excellapay
Does it get passed review if it does not work in test flight?

**Comment by jamesmontemagno** [comment] 2021-02-07 23:08
Closing as I have verified that this is not an issue at all and just testing issue

**Closed by jamesmontemagno** 2021-02-07 23:08 UTC
Labels: up-for-grabs
