### ISSUE TITLE
[iOS] Occasional phantom purchases

### ISSUE THREAD

**Issue by BioTurboNick** [jamesmontemagno/InAppBillingPlugin#218] opened 2019-04-01 16:23 UTC
## Bug Information

Version Number of Plugin: 2.0.0
Device Tested On: iOS unknown version
Version of Xamarin: 3.6

For months now I've been getting occasional reports of phantom purchases via AppCenter. I have AppCenter set to report successful purchases, and it is coded to do this when the object returned by `PurchaseAsync()` has `State == PurchaseState.Purchased`. Somehow, this state is occurring while the AppStore shows no purchases.

Real purchases do occur and are recorded normally. Purchase failures also occur and are reported as such.

I can't tell from the code where there might be an opening for this, but I note that the default value for the PurchaseState enumeration is "Purchased". Changing the default value would at least eliminate this as a cause.

**Comment by BioTurboNick** [comment] 2019-04-03 22:35
It occurs to me that this might be a manifestation of a bug on my end. Is it the case that iOS doesn't have the concept of an "already purchased" API response, and just returns a success notification?

If so, this can be closed.

**Comment by ivanicin** [comment] 2019-04-07 20:49
Also on the App Store statistics you cannot see refunds but just a net result which makes data hard to compare and conclude anything.

**Comment by jamesmontemagno** [comment] 2022-02-10 21:51
Unable to reproduce and closing due to age of issue

**Closed by jamesmontemagno** 2022-02-10 21:51 UTC
Labels: up-for-grabs
