### ISSUE TITLE
IInAppBillingVerifyPurchase for iOS devices - occasionally returns null for signature, productId and transactionId

### ISSUE THREAD

**Issue by mgoodfellow** [jamesmontemagno/InAppBillingPlugin#169] opened 2018-06-20 17:16 UTC
## Bug Information

Version Number of Plugin: 1.2.4.138-beta  (Seen on all versions up to this version)
Device Tested On: iOS Devices (v10 upwards)
Simulator Tested On: N/A
Version of VS: 15.7.3
Version of Xamarin: Forms 2.5.1.444934
Versions of other things you are using: N/A

### Steps to reproduce the Behavior

We suffer this issue in every 1% of iOS in app purchases. I have been trying to track it down for a long time now, so I have added some tracing to our mobile app to try to pinpoint the behaviour.

### Expected Behavior

IInAppBillingVerifyPurchase to be called with valid data for `signedData`, `productId` and `transactionId` for an iOS purchase (99% of cases). We do not require the signature for iOS verification.

### Actual Behavior

IInAppBillingVerifyPurchase has only the signedData param populated.

When we run this signed data via Apple on our server to validate the purchase, it is correctly processed, but our own verification code fails as we cannot compare the retrieved transactionId from the Apple servers with the transactionId reported via the mobile app.

### Code snippet

Available on request - pretty much following your blog post exactly, and using the links you provided for the server side verification stuff.

### Screenshotst

N/A

**Comment by mgoodfellow** [comment] 2018-06-20 17:48
I see that it should be handled via `PurchaseAsync` here - https://github.com/jamesmontemagno/InAppBillingPlugin/blob/bdfc1ac3249b8cbdf0c4eac6a107b2c1c10b2d7d/src/Plugin.InAppBilling.iOS/InAppBillingImplementation.cs#L227

This implies that the `paymentObserver` here - https://github.com/jamesmontemagno/InAppBillingPlugin/blob/bdfc1ac3249b8cbdf0c4eac6a107b2c1c10b2d7d/src/Plugin.InAppBilling.iOS/InAppBillingImplementation.cs#L279 is returning a transaction object with the `TransactionIdentifier` not being set

**Comment by devology-rob** [comment] 2019-01-21 10:36
Is there a known root cause for this yet?  For example, could it be due to jailbroken iPhones and therefore not all the data is sent through?  Or is this a bug that could affect genuine/real purchases?

**Comment by Sebastian1989101** [comment] 2019-01-21 23:20
I have the same issue and tested it with a devices that has get the purchase from a unlocking code. When I now use the restore mechanic the purchase id and transaction id are missing. Can this be fixed somehow? Because it totally destroys server side verification if it won't work properly.

**Comment by jamesmontemagno** [comment] 2022-02-10 21:53
I believe this is fixed. closing due to age and mass changes in library

**Closed by jamesmontemagno** 2022-02-10 21:53 UTC
Labels: ios
