### ISSUE TITLE
Android: NullReferenceException 

### ISSUE THREAD

**Issue by eliotg** [jamesmontemagno/InAppBillingPlugin#182] opened 2018-08-23 05:33 UTC
## Bug Information
InAppBillingImplementation+InAppBillingServiceConnection.OnServiceConnected: System.NullReferenceException: Object reference not set to an instance of an object
Stack trace:  https://gist.github.com/eliotg/32f0634d02b4846ed8229e2e04354244

Looking at the current code, it's hard to imagine which line could generate this exact stack trace.

Version Number of Plugin: 1.2.4
Device Tested On: Samsung Galaxy S7, Android 8.0.0
Version of VS: 2017
Version of Xamarin: whatever was current as of June 19, Xamarin.Forms package = 2.5.0.280555
Versions of other things you are using: Microsoft.AppCenter 1.6.0

### Steps to reproduce the Behavior
Precise steps unknown.  We didn't know to corner the user until after he left the room.

### Expected Behavior
Shouldn't crash.

### Actual Behavior
It did.

### Code snippet
Most likely, this was an attempt to check price or purchase our (only) subscription, so either:
`e = await CrossInAppBilling.Current.GetProductInfoAsync(ItemType.Subscription, new string[] { SubToUse() });`
or
`var purchase = await CrossInAppBilling.Current.PurchaseAsync(SubToUse(), ItemType.Subscription, "apppayload");`
We already did work to handle when the user isn't setup in the Play Store, so I wouldn't think that would be it.

### Screenshots
None, sorry.

**Comment by jamesmontemagno** [comment] 2018-08-30 18:08
See bottom to initialize CurrentActivity plugin: https://jamesmontemagno.github.io/InAppBillingPlugin/GettingStarted.html

**Comment by eliotg** [comment] 2018-08-30 18:19
I apologize if I wasn't clear.  That's not our entire purchase code, but what I thought was relevant.  This code has allowed hundreds of users to purchase successfully, so it's clearly not a trivial bug on our part.

Here's a less condensed version of the relevant code:
            try
            {
                // connect
                // SarTag issue #166: NullReferenceException in Android OnServiceConnected()
                // TODO: remove if IABP issue is resolved satisfactorily
                try
                {
                    if (!await CrossInAppBilling.Current.ConnectAsync())
                    {
                        Analytics.TrackEvent("Billing:BuySub ConnectionError");
                        return Result.ConnectionError;
                    }
                }
                catch (NullReferenceException nre)
                {
                    Util.TrackException("Billing:BuySub NullReference(OnServiceConnected)", nre);
                    return Result.ConnectionError;
                }

                // fetch the price again--this is supposed to help with "cannot connect" errors
                e = await CrossInAppBilling.Current.GetProductInfoAsync(ItemType.Subscription, 
                                                                        new string[] { SubToUse() });

                //
                // then try the actual purchase
                //
                var purchase = await CrossInAppBilling.Current.PurchaseAsync(SubToUse(),
                                                                             ItemType.Subscription,
                                                                             "apppayload");

                // if unsuccessful
                if ((purchase == null) || (PurchaseState.Canceled == purchase.State))
                {
                    Analytics.TrackEvent("Billing:BuySub purchase==null|canceled");

                    // assume this is ok
                    return Result.Cancelled;
                }

                // woot!
                Analytics.TrackEvent("Billing:BuySub success", new Dictionary<string, string> {
                                        { "ProductId", purchase.ProductId }, { "PurchaseState", purchase.State.ToString() } });

                // tell the caller
                return Result.LicenseActive;
            }
            catch (InAppBillingPurchaseException iabpe)
            {
                // this isn't a problem
                if (PurchaseError.UserCancelled == iabpe.PurchaseError)
                {
                    Analytics.TrackEvent("Billing:BuySub canceled");
                    return Result.Cancelled;
                }
                // nor is this our fault or anything we can do something about
                // "user is not allowed to authorize payments"
                if (PurchaseError.PaymentNotAllowed == iabpe.PurchaseError)
                {
                    Analytics.TrackEvent("Billing:BuySub userNotPayAuthz");
                    return Result.Cancelled;
                }

                // but otherwise, it is a problem of some sort
                Dictionary<string, string> d = new Dictionary<string, string>() {
                                                { "PurchaseError", iabpe.PurchaseError.ToString() } };
                Util.TrackException("Billing:BuySub", iabpe, d);

                // and posssibly redirect the error type
                if (iabpe.Message.Contains("Cannot connect to iTunes Store"))
                    return Result.ConnectionError;
                else
                    return Result.Exception;
            }
            catch (Exception ex)
            {
                Util.TrackException("Billing:BuySub", ex);
                return Result.Exception;
            }
            finally
            {
                //Disconnect, it is okay if we never connected, this will never throw an exception
                await CrossInAppBilling.Current.DisconnectAsync();
            }

**Comment by jamesmontemagno** [comment] 2018-08-30 19:29
I am missing your context a bit here. Does this seem to work for some users? not for others? 

Also looks like you are using an old version. I fixed null checks in this area around 7 months ago: https://github.com/jamesmontemagno/InAppBillingPlugin/commit/9a97e3ba55a4e8502bfe30e51bb88e0403e7e9e4

**Comment by jamesmontemagno** [comment] 2018-08-30 19:29
duplicate of #75 for reference

**Closed by jamesmontemagno** 2018-08-30 19:29 UTC
