### ISSUE TITLE
Android nothing works / iOS restore failed

### ISSUE THREAD

**Issue by Sebastian1989101** [jamesmontemagno/InAppBillingPlugin#36] opened 2017-04-01 21:00 UTC
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 1.1.0.34-beta
Device Tested On: Multiple iOS devices (iOS 9.3, 10.1, 10.3) / Android Nexus 7 and 4 both with Android 4.4
Simulator Tested On: -

### Expected Behavior 
Working In-App-Purchases

### Actual Behavior 
I use the plugin in version 1.1.0.24-beta in a other app - there anything is working (or at least I got no bug reports from users / trouble while testing). WIth version 1.1.0.34-beta Android does not working (Purchase  failed - restore works for usesd promotion codes). Also I got annoying "Please sign in" pop ups over and over again on iOS since testing. I can share you my sourcecode if you want to test it, or maybe something is wrong there because the VerifyPurchase-Method parameter changed and I can't find anything about the change in the documentation. 

### Steps to reproduce the Behavior
Using the plugin. 

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment] 2017-04-07 16:22
I believe last week iTunes was having issues, please try again.

**Comment by jamesmontemagno** [comment] 2017-05-18 18:02
Closing as can't reproduce

**Closed by jamesmontemagno** 2017-05-18 18:02 UTC
